name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Test Building the Docker image
      run: docker build . --file Dockerfile --tag crosscopy-mq-notification-service:$(date +%s)
