# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - .github/**
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - .github/**

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Start Docker Services
        run: docker-compose up -d

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      
      - name: Stop Docker Containers
        run: docker-compose down
